image: ubuntu:16.04
stages:
  - dev
  - staging
  - production

before_script:
  - apt-get update -qq && apt-get install -y -qq python3
  - python3 --version

deva:
  script:
    - python3 test.py
  stage: dev

devb:
  script:
    - echo "true"
  stage: dev
  only:
    - dev

staging:
  script:
    - python3 test.py
  stage: staging
  only:
    - staging
    - master
    
production:
  script:
    - python3 test.py
  stage: production
  only:
    - master
  environment: production
